# Generated by Django 3.2.12 on 2022-04-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_user1_status',
            field=models.IntegerField(default=0, verbose_name='状态1'),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_user2_status',
            field=models.IntegerField(default=0, verbose_name='状态2'),
        ),
    ]
